### ISSUE TITLE
Failure downloading due object names w/ spaces

### ISSUE THREAD

**Issue by brandonmytty** [EMCECS/ecs-browser#15]
It seems the browser doesn’t handle those yet when they are the last of the 1000 objects returned in a batch. The code downloads the current batch correctly, including those files, but then fails when it requests the next batch after that.

Please add an enhancement for special character handling, as there are probably other special characters that would cause it to fail the same way.

**Comment by DavidASeibert** [comment]
Fixed in release v1.0.1.
