### ISSUE TITLE
Capability to download directory / folder

### ISSUE THREAD

**Issue by navulirs** [EMCECS/ecs-browser#4]
Hello - it appears ECS browser doesn't support downloading a folder. 
![emc-ecs-directory-download1](https://user-images.githubusercontent.com/4923947/42957906-914481f8-8b49-11e8-92e2-dd2d20b661a6.jpg)

Can you please address this issue?

Thank you.

**Comment by DavidASeibert** [comment]
Finished on v1.0.0rc1
