### ISSUE TITLE
Request - List contents of bucket > 1000

### ISSUE THREAD

**Issue by brandonmytty** [EMCECS/ecs-browser#9]
Want to be able to return all "folders"/objects in a bucket in the browser, right now limited to 1000. This means if there is an object that exceeds the 1000 mark, the only way to find it in the browser is by copy and paste (have to pull name from different source).

**Comment by DavidASeibert** [comment]
Fixed in v1.0.0rc2

**Comment by DavidASeibert** [comment]
It's ready, @brandonmytty
